# Generated by Django 5.1.7 on 2025-04-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_em_estoque',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
